### ISSUE TITLE
On the UI for this endpoint 78.159.113.46 the Request History page displays Error Getting Transaction Data

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/icap-infrastructure#23]
Go to http://78.159.113.46:31829/
Request History

**Comment by azopat** [comment]
@mahnouman 
That server is not stable because it's where i do integrations.
We should build a new server and there we will not have this error. Do you want me to build one which will be only for your testings ?

**Comment by mahnouman** [comment]
@azopat yes please create a new server

**Comment by azopat** [comment]
Ok you can use this endpoint now 
http://78.159.113.47:31829

**Comment by NadHodeGW** [comment]
@azopat, files processed do not appear in the transaction log for that endpoint.
There is a new server i'm using that shows transactions ok but the policy screen still displays error getting Policy data. Can you take a look at that please
http://34.244.23.244:31829/

![image](https://user-images.githubusercontent.com/61200359/105347121-590fb100-5bde-11eb-9b66-688e76a2877e.png)

**Comment by GINAGC** [comment]
can we close this one?
