### ISSUE TITLE
Document and test Creating ICAP-Servers on AWS

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/icap-infrastructure#30]
keep creating ICAP servers https://github.com/samarthdd/icap-infrastructure/blob/k8-main/HOW-TO-Create-Icap-VMs.md, see updates on channel k8-icap-aws

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/105376034-525d5a00-5c2f-11eb-9971-94350e4b3793.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/105377004-5a69c980-5c30-11eb-90d7-97a60b6a95ff.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/105377964-57bba400-5c31-11eb-8c92-b80d419a8e82.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/105380022-7458db80-5c33-11eb-9513-55babc2d3919.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/105380046-7c188000-5c33-11eb-883d-7e371ba111b6.png)
