### ISSUE TITLE
4 load balancers

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/icap-infrastructure#31]
- all ICAP endpoints (we already have this server)
- All rancher endpoints , i.e. the 3 we have been given (we need this HA proxy) - only needs TLS on port 443 (for ICAP)
- all AWS endpoints , including the eu and us endpoints  (we need this HA proxy)
- all VMWare endpoints (we need this HA proxy)

they should be called:

- all.icap.glasswall-icap.com
- rancher.icap.glasswall-icap.com
- aws.icap.glasswall-icap.com
- vmware.icap.glasswall-icap.com

**Comment by naderaly** [comment]
@GINAGC @dtollaku , those servers are ready just need to add dns entry which I am reaching out with some who has access atm.
Also as far as I know we don't have ICAP servers on vmware .. who can confirm this ? and if I am wrong I'll need those servers IPs
