### ISSUE TITLE
Review new release from SOW team

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/icap-infrastructure#36]
we have new release from SOW team:
https://github.com/filetrust/mvp-icap-service/releases/tag/v1.1.0
https://github.com/filetrust/icap-infrastructure/releases/tag/v0.5.0
Updates to enable  ICAP Server configuration to be provided from ConfigMaps"

Review with @mahnouman before starting this task for some guidance.

**Comment by gurunathg** [comment]
Completed initial round of testing as per https://github.com/k8-proxy/icap-infrastructure/blob/k8-main/HOW-TO-Refresh.md
Below are observations:
1. Statement - Identify any other newly created template from upstream using azure files and make it to use persistent volume - at end of document is bit unclear regarding what is to be carried out 
2. Next steps after copying custom templates is missing. Currently document ends with steps of copying custom templates

**Comment by mahnouman** [comment]
Hello @azopat ,, please work with @gurunathg to get a better idea about what is unclear in the documentation and adjust it accordingly. Thank you

**Comment by GINAGC** [comment]
This is related to https://github.com/k8-proxy/icap-infrastructure/issues/37
