### ISSUE TITLE
start and stop servers on a continuous basis across multiple availability zones and data centers

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/icap-infrastructure#43]
start and stop servers on a continuous basis s across multiple availability zones and data centers (programmatically). This should be using the current EC2-SOW ami and the EC2-Patric ami  (which has the performance improvement)

channel: k8-icap-aws

**Comment by mahnouman** [comment]
Work moved to: https://github.com/k8-proxy/k8-icap-cloud-formation
