### ISSUE TITLE
CF stack process

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/icap-infrastructure#48]
From channel: 
there was probably only one server that was healthy
the others where bad (which is weird since the should all be the same)
this was not the most recent AMI
what we need now is to delete that CF deployment (which should delete all components of it)
deploy a new CF with 5 servers
trigger a new test via http://18.203.243.63/
if that test is good, add that LB to http://all.icap.glasswall-icap.com:32700/

**After that, add and confirm which from the following are added to CF:**
- see traffic
- seeing the need for more servers
- adding more servers
- deleting non-responsive servers
- adding more load when servers can handle it
one big prob area is that we still don't have a good way to determine the health of the servers

**Comment by mahnouman** [comment]
Work moved to: https://github.com/k8-proxy/k8-icap-cloud-formation
