### ISSUE TITLE
CD using terraform

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/icap-infrastructure#54]
deploy one or multiple instances and also to be able to destroy it(or them) in one command

**Comment by azopat** [comment]
@GINAGC  @dtollaku  @mahnouman 
Is there a repo where i should push this terraform code ? or should i create a new repo ?

**Comment by mahnouman** [comment]
Hello @azopat please submit it here:
https://github.com/k8-proxy/k8-icap-terraform
