### ISSUE TITLE
OVA for ICAP server with the docker images pulled. 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/icap-infrastructure#62]
4 updates needed for the next OVA version:

1.- Update from main from SOW - include ICAP server and management UI updates https://github.com/filetrust/icap-management-ui
2.- Update in logs to be level 6 or 7
3.- Update to contain the docker images already pulled, so it can be installed on the environment without internet access. 
4.- Fix to k3s issue 

Problem: ICAP server, the issue is that will not be able to pull the docker images and the PODs will be in crash status.
Goal: Create OVA for ICAP server that contains the docker images already pulled.

**Comment by gurunathg** [comment]
So far, we have completed storing of images in local docker registry. Working on updating helm charts to use local docker registry

**Comment by gurunathg** [comment]
Updates:
1. We have updated setup process of build to make icap server work in offline mode
2. Tested in AWS with latest AMI - ami-00e4ebf5763b7e449
3. Latest OVA link: s3://glasswall-sow-ova/vms/icap-server/icap-server-1826d81c4ef65d63ac91f4e1b7a7e47fe88774ab-65.ova
4. Updated log verbosity to 7 from 10
5. Management UI updated with latest SOW version
